---
  - block: 
    - name: Update /etc/apt/sources.list
      template:
        src: etc/apt/sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644

    - name: Upgrade packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Nvidia required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libasound2
        - libgles2
        - libpangoft2-1.0-0
        - libxkbcommon0
        - libharfbuzz0b
        - libwayland-egl1
        - libwayland-cursor0
        - libunwind8
        - libpng16-16
        - libpixman-1-0
        - libjpeg-turbo8
        - libinput10
        - libevdev2
        - libcairo2
        - device-tree-compiler
        - iso-codes
        - libffi6
        - libncursesw5
        - libpython3-stdlib
        - libpython3.8-minimal
        - libpython3.8-stdlib
        - libtinfo5
        - python
        - python3-minimal
        - python3.8
        - libglvnd0
        - libdrm-common
        - libdrm2
        - libegl-mesa0
        - libegl1
        - libgbm1
        - libglapi-mesa
        - libwayland-server0
        - libx11-xcb1
        - libxcb-dri3-0
        - libxcb-present0
        - libxcb-sync1
        - libxcb-xfixes0
        - libxshmfence1
        - libgstreamer1.0-0
        - libgstreamer-plugins-bad1.0-0
        - libpangocairo-1.0-0

    - name: Install core packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - build-essential
        - btrfs-tools
        - cmake
        - curl
        - dnsutils
        - htop
        - iotop
        - isc-dhcp-client
        - iputils-ping
        - kmod
        - linux-firmware
        - locales
        - net-tools
        - netplan.io
        - pciutils
        - python3-dev
        - ssh
        - sudo
        - systemd
        - udev
        - unzip
        - usbutils
        - vim
        - wpasupplicant

    - name: Generate locales
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
      loop:
        - ssh
        - systemd-networkd

    - name: Update network conf
      template:
        src: etc/netplan/netcfg.yaml
        dest: /etc/netplan/netcfg.yaml
        owner: root
        group: root
        mode: 0644

    - name: Create new user
      user:
        name: "{{ new_user.name }}"
        shell: "{{ new_user.shell }}"
        password: "{{ new_user.password | password_hash('sha512') }}"
        create_home: yes
        groups: sudo
        state: present

    - name: Download pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      shell: python3.8 /tmp/get-pip.py --user
      become: yes
      become_user: "{{ new_user.name }}"
    # to avoid everything stops if one package name is wrong hence is not found for example
    ignore_errors: yes 